from enum import StrEnum


class Layer(StrEnum):
    SOURCE = "SOURCE"
    SEMANTIC = "SEMANTIC"
    ARGUMENT = "ARGUMENT"
    LEARNING = "LEARNING"
    CONTEXT = "CONTEXT"


class NodeType(StrEnum):
    PAPER = "PAPER"
    SECTION = "SECTION"
    PARAGRAPH = "PARAGRAPH"
    SOURCE_SPAN = "SOURCE_SPAN"
    FIGURE = "FIGURE"
    TABLE = "TABLE"
    EQUATION = "EQUATION"
    REFERENCE = "REFERENCE"
    FIRST_PRINCIPLE = "FIRST_PRINCIPLE"
    MATHEMATICAL_CONCEPT = "MATHEMATICAL_CONCEPT"
    MATHEMATICAL_THEOREM = "MATHEMATICAL_THEOREM"
    MATHEMATICAL_METHOD = "MATHEMATICAL_METHOD"
    PHYSICAL_LAW = "PHYSICAL_LAW"
    PHYSICAL_CONCEPT = "PHYSICAL_CONCEPT"
    PHYSICAL_QUANTITY = "PHYSICAL_QUANTITY"
    PHENOMENON = "PHENOMENON"
    CHEMICAL_CONCEPT = "CHEMICAL_CONCEPT"
    MATERIAL = "MATERIAL"
    THEORY = "THEORY"
    MODEL = "MODEL"
    DEFINITION = "DEFINITION"
    ASSUMPTION = "ASSUMPTION"
    APPROXIMATION = "APPROXIMATION"
    METHOD = "METHOD"
    ALGORITHM = "ALGORITHM"
    PROCESS = "PROCESS"
    DEVICE = "DEVICE"
    ARCHITECTURE = "ARCHITECTURE"
    EXPERIMENT = "EXPERIMENT"
    SIMULATION = "SIMULATION"
    DATASET = "DATASET"
    PARAMETER = "PARAMETER"
    METRIC = "METRIC"
    RESEARCH_PROBLEM = "RESEARCH_PROBLEM"
    MOTIVATION = "MOTIVATION"
    RESEARCH_GAP = "RESEARCH_GAP"
    HYPOTHESIS = "HYPOTHESIS"
    CLAIM = "CLAIM"
    OBSERVATION = "OBSERVATION"
    EVIDENCE = "EVIDENCE"
    RESULT = "RESULT"
    CONCLUSION = "CONCLUSION"
    CONTRIBUTION = "CONTRIBUTION"
    INNOVATION = "INNOVATION"
    LIMITATION = "LIMITATION"
    OPEN_QUESTION = "OPEN_QUESTION"
    PRIOR_WORK = "PRIOR_WORK"


class Relation(StrEnum):
    CONTAINS = "CONTAINS"
    MENTIONS = "MENTIONS"
    DEFINES = "DEFINES"
    DESCRIBES = "DESCRIBES"
    DERIVES_FROM = "DERIVES_FROM"
    MATHEMATICALLY_DERIVES_FROM = "MATHEMATICALLY_DERIVES_FROM"
    DEPENDS_ON = "DEPENDS_ON"
    PREREQUISITE_OF = "PREREQUISITE_OF"
    USES = "USES"
    APPLIES = "APPLIES"
    IMPLEMENTS = "IMPLEMENTS"
    ASSUMES = "ASSUMES"
    APPROXIMATES = "APPROXIMATES"
    EXPLAINS = "EXPLAINS"
    CAUSES = "CAUSES"
    AFFECTS = "AFFECTS"
    MEASURES = "MEASURES"
    MEASURED_BY = "MEASURED_BY"
    SIMULATES = "SIMULATES"
    SIMULATED_BY = "SIMULATED_BY"
    VALIDATES = "VALIDATES"
    VALIDATED_BY = "VALIDATED_BY"
    SUPPORTS = "SUPPORTS"
    SUPPORTED_BY = "SUPPORTED_BY"
    CONTRADICTS = "CONTRADICTS"
    COMPARES_WITH = "COMPARES_WITH"
    EXTENDS = "EXTENDS"
    IMPROVES = "IMPROVES"
    MOTIVATES = "MOTIVATES"
    ADDRESSES = "ADDRESSES"
    SOLVES = "SOLVES"
    PRODUCES = "PRODUCES"
    RESULTS_IN = "RESULTS_IN"
    CITES = "CITES"
    CITED_BY = "CITED_BY"
    EVIDENCE_FOR = "EVIDENCE_FOR"
    PART_OF = "PART_OF"


class EpistemicStatus(StrEnum):
    PAPER_EXPLICIT = "PAPER_EXPLICIT"
    PAPER_IMPLICIT = "PAPER_IMPLICIT"
    AUTHOR_CLAIM = "AUTHOR_CLAIM"
    OBSERVED_DATA = "OBSERVED_DATA"
    REFERENCE_DERIVED = "REFERENCE_DERIVED"
    BACKGROUND_KNOWLEDGE = "BACKGROUND_KNOWLEDGE"
    AI_INTERPRETATION = "AI_INTERPRETATION"
    AI_DERIVATION = "AI_DERIVATION"
    AI_HYPOTHESIS = "AI_HYPOTHESIS"
    UNVERIFIED = "UNVERIFIED"
    CONFLICTING = "CONFLICTING"
    UNKNOWN = "UNKNOWN"
    NOT_SPECIFIED_IN_PAPER = "NOT_SPECIFIED_IN_PAPER"


class VerificationStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    SUPPORTED = "SUPPORTED"
    VERIFIED = "VERIFIED"
    DISPUTED = "DISPUTED"
    REJECTED = "REJECTED"
    STALE = "STALE"


class JobStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    ENTITY_EXTRACTION = "ENTITY_EXTRACTION"
    GRAPH_BUILDING = "GRAPH_BUILDING"
    READY = "READY"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ReviewScope(StrEnum):
    SOURCE_ATTRIBUTION = "SOURCE_ATTRIBUTION"
    SCIENTIFIC_VALIDITY = "SCIENTIFIC_VALIDITY"


SOURCE_TYPES = {
    NodeType.PAPER,
    NodeType.SECTION,
    NodeType.PARAGRAPH,
    NodeType.SOURCE_SPAN,
    NodeType.FIGURE,
    NodeType.TABLE,
    NodeType.EQUATION,
    NodeType.REFERENCE,
}
ARGUMENT_TYPES = {
    NodeType.CLAIM,
    NodeType.HYPOTHESIS,
    NodeType.OBSERVATION,
    NodeType.EVIDENCE,
    NodeType.RESULT,
    NodeType.CONCLUSION,
    NodeType.CONTRIBUTION,
    NodeType.INNOVATION,
    NodeType.LIMITATION,
    NodeType.OPEN_QUESTION,
}


def valid_layer(node_type: str, layer: str) -> bool:
    kind = NodeType(node_type)
    value = Layer(layer)
    if kind in SOURCE_TYPES:
        return value == Layer.SOURCE
    if kind in ARGUMENT_TYPES:
        return value == Layer.ARGUMENT
    if kind == NodeType.FIRST_PRINCIPLE:
        return value in {Layer.LEARNING, Layer.SEMANTIC}
    if kind == NodeType.PRIOR_WORK:
        return value == Layer.CONTEXT
    if kind in {NodeType.ASSUMPTION, NodeType.APPROXIMATION}:
        return value in {Layer.SEMANTIC, Layer.ARGUMENT}
    return value == Layer.SEMANTIC
