"""canonical source graph evidence and jobs

Revision ID: 10f9a4e1b6e1
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "10f9a4e1b6e1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("parser", sa.String(), nullable=False),
        sa.Column("parser_version", sa.String(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_hash"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("pipeline_version", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.Double(), nullable=False),
        sa.Column("lease_token", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id"),
    )
    op.create_index("jobs_queue", "jobs", ["status", "lease_until"], unique=False)
    op.create_table(
        "knowledge_nodes",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("epistemic_status", sa.String(), nullable=False),
        sa.Column("uncertainty_reason", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("verification_status", sa.String(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1"),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_nodes_paper_id"), "knowledge_nodes", ["paper_id"], unique=False
    )
    op.create_table(
        "paper_pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("width", sa.Double(), nullable=False),
        sa.Column("height", sa.Double(), nullable=False),
        sa.Column("rotation", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "number"),
    )
    op.create_index(op.f("ix_paper_pages_paper_id"), "paper_pages", ["paper_id"], unique=False)
    op.create_table(
        "verification_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("object_kind", sa.String(), nullable=False),
        sa.Column("reviewer", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column("object_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_edges",
        sa.Column("source_node_id", sa.String(length=36), nullable=False),
        sa.Column("target_node_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("verification_status", sa.String(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1"),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["knowledge_nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["knowledge_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_edges_paper_id"), "knowledge_edges", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_edges_source_node_id"),
        "knowledge_edges",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_edges_target_node_id"),
        "knowledge_edges",
        ["target_node_id"],
        unique=False,
    )
    op.create_table(
        "source_spans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("page_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["paper_pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_spans_paper_id"), "source_spans", ["paper_id"], unique=False)
    op.create_table(
        "source_anchors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("span_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=False),
        sa.Column("end_char", sa.Integer(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("start_char >= 0 AND end_char > start_char"),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["span_id"],
            ["source_spans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_anchors_paper_id"), "source_anchors", ["paper_id"], unique=False
    )
    op.create_index(op.f("ix_source_anchors_span_id"), "source_anchors", ["span_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("supports_object_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(), nullable=False),
        sa.Column("support_type", sa.String(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("verification_status", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anchor_id"],
            ["source_anchors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supports_object_id"],
            ["knowledge_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_supports_object_id"), "evidence", ["supports_object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_supports_object_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_source_anchors_span_id"), table_name="source_anchors")
    op.drop_index(op.f("ix_source_anchors_paper_id"), table_name="source_anchors")
    op.drop_table("source_anchors")
    op.drop_index(op.f("ix_source_spans_paper_id"), table_name="source_spans")
    op.drop_table("source_spans")
    op.drop_index(op.f("ix_knowledge_edges_target_node_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_source_node_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_paper_id"), table_name="knowledge_edges")
    op.drop_table("knowledge_edges")
    op.drop_table("verification_records")
    op.drop_index(op.f("ix_paper_pages_paper_id"), table_name="paper_pages")
    op.drop_table("paper_pages")
    op.drop_index(op.f("ix_knowledge_nodes_paper_id"), table_name="knowledge_nodes")
    op.drop_table("knowledge_nodes")
    op.drop_index("jobs_queue", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("papers")
    # ### end Alembic commands ###
